language: php

php:
  - 5.6
  - 7.3

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - composer install --prefer-source --no-interaction

script:
  - composer cs-check

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
