language: php

php:
  - 5.6

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - composer install --prefer-source --no-interaction

script:
  - composer cs-check

notifications:
  email: false
